# This file is generated by scripts/update-formula.hell. DO NOT EDIT.

class Hell < Formula
  desc "A Haskell-based shell scripting language"
  homepage "https://github.com/chrisdone/hell"
  version "2026-05-02"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/Portfoligno/homebrew-hell/releases/download/2026-05-02/hell-aarch64-apple-darwin.tar.gz"
      sha256 "dad9da239413e28df61a272931b546f8a4859acf92ced3e1f9ce8845ba0cae92"
    end
    on_intel do
      url "https://github.com/Portfoligno/homebrew-hell/releases/download/2026-05-02/hell-x86_64-apple-darwin.tar.gz"
      sha256 "3e45e2f0e7297b1b6d2adc191d244bb33381deb5022182c7869f2a99b6c3dad7"
    end
  end

  def install
    bin.install "hell"
  end

  test do
    (testpath/"test.hell").write <<~HELL
      main = Text.putStrLn "hello from hell"
    HELL
    assert_equal "hello from hell", shell_output("\#{bin}/hell \#{testpath}/test.hell").strip
  end
end
